// <auto-generated />
namespace DiversityService.API.WebHost.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CollectionId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CollectionId));
        
        string IMigrationMetadata.Id
        {
            get { return "201406191750523_CollectionId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
