//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityService.API.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiversityService.API.Resources.Messages", typeof(Messages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Event TimeStamp lies in the future..
        /// </summary>
        public static string Event_FutureDate {
            get {
                return ResourceManager.GetString("Event_FutureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Event must have a Location Description..
        /// </summary>
        public static string Event_NoLocation {
            get {
                return ResourceManager.GetString("Event_NoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Transaction Guid is missing..
        /// </summary>
        public static string No_TransactionGuid {
            get {
                return ResourceManager.GetString("No_TransactionGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Series Code provided is more than 50 characters in length..
        /// </summary>
        public static string Series_CodeTooLong {
            get {
                return ResourceManager.GetString("Series_CodeTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Series must start before it ends..
        /// </summary>
        public static string Series_EndBeforeStart {
            get {
                return ResourceManager.GetString("Series_EndBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Series may not start or end in the future..
        /// </summary>
        public static string Series_FutureDate {
            get {
                return ResourceManager.GetString("Series_FutureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Description may not be null, empty or consist entirely of whitespace..
        /// </summary>
        public static string Series_NoDescription {
            get {
                return ResourceManager.GetString("Series_NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Series must have a start date.
        /// </summary>
        public static string Series_NoStartDate {
            get {
                return ResourceManager.GetString("Series_NoStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no series with this id.
        /// </summary>
        public static string Series_NotFound {
            get {
                return ResourceManager.GetString("Series_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Specimen CollectionDate lies in the Future..
        /// </summary>
        public static string Specimen_FutureDate {
            get {
                return ResourceManager.GetString("Specimen_FutureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CollectionDate is a required Member..
        /// </summary>
        public static string Specimen_NoCollectionDate {
            get {
                return ResourceManager.GetString("Specimen_NoCollectionDate", resourceCulture);
            }
        }
    }
}
