//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityService.DB.TaxonNames
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TaxonNames : DbContext
    {
        public TaxonNames()
            : base("name=TaxonNames")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        [DbFunction("TaxonNames", "DiversityMobile_TaxonList")]
        public virtual IQueryable<DiversityMobile_TaxonList_Result> DiversityMobile_TaxonList(Nullable<int> listID)
        {
            var listIDParameter = listID.HasValue ?
                new ObjectParameter("ListID", listID) :
                new ObjectParameter("ListID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DiversityMobile_TaxonList_Result>("[TaxonNames].[DiversityMobile_TaxonList](@ListID)", listIDParameter);
        }
    
        [DbFunction("TaxonNames", "DiversityMobile_TaxonListsForUser")]
        public virtual IQueryable<DiversityMobile_TaxonListsForUser_Result> DiversityMobile_TaxonListsForUser(string login)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DiversityMobile_TaxonListsForUser_Result>("[TaxonNames].[DiversityMobile_TaxonListsForUser](@Login)", loginParameter);
        }
    }
}
