//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityService.DB.TaxonNames
{
    using System;
    
    public partial class TaxonName
    {
        public string NameURI { get; set; }
        public string TaxonNameCache { get; set; }
        public string TaxonNameSinAuthors { get; set; }
        public string GenusOrSupragenericName { get; set; }
        public string SpeciesEpithet { get; set; }
        public string InfraspecificEpithet { get; set; }
        public string Synonymy { get; set; }
        public string Family { get; set; }
        public string Order { get; set; }
        public string AcceptedNameCache { get; set; }
        public string AcceptedNameURI { get; set; }
    }
}
