//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityService.Collection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analysis
    {
        public Analysis()
        {
            this.AnalysisResult = new HashSet<AnalysisResult>();
            this.Analysis1 = new HashSet<Analysis>();
            this.IdentificationUnitAnalysis = new HashSet<IdentificationUnitAnalysis>();
        }
    
        public int AnalysisID { get; set; }
        public Nullable<int> AnalysisParentID { get; set; }
        public string DisplayText { get; set; }
        public string Description { get; set; }
        public string MeasurementUnit { get; set; }
        public string Notes { get; set; }
        public string AnalysisURI { get; set; }
        public Nullable<bool> OnlyHierarchy { get; set; }
        public System.Guid RowGUID { get; set; }
    
        public virtual ICollection<AnalysisResult> AnalysisResult { get; set; }
        public virtual ICollection<Analysis> Analysis1 { get; set; }
        public virtual Analysis Analysis2 { get; set; }
        public virtual ICollection<IdentificationUnitAnalysis> IdentificationUnitAnalysis { get; set; }
    }
}
