//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityService.Collection
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalysisResult
    {
        public int AnalysisID { get; set; }
        public string AnalysisResult1 { get; set; }
        public string Description { get; set; }
        public string DisplayText { get; set; }
        public Nullable<short> DisplayOrder { get; set; }
        public string Notes { get; set; }
        public string LogInsertedBy { get; set; }
        public Nullable<System.DateTime> LogInsertedWhen { get; set; }
        public string LogUpdatedBy { get; set; }
        public Nullable<System.DateTime> LogUpdatedWhen { get; set; }
        public System.Guid RowGUID { get; set; }
    
        public virtual Analysis Analysis { get; set; }
    }
}
