//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityService.Collection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Collection : DbContext
    {
        public Collection()
            : base("name=Collection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analysis> Analysis { get; set; }
        public virtual DbSet<AnalysisResult> AnalysisResult { get; set; }
        public virtual DbSet<Event> CollectionEvent { get; set; }
        public virtual DbSet<EventImage> CollectionEventImage { get; set; }
        public virtual DbSet<EventProperty> CollectionEventProperty { get; set; }
        public virtual DbSet<EventSeries> EventSeries { get; set; }
        public virtual DbSet<EventSeriesImage> CollectionEventSeriesImage { get; set; }
        public virtual DbSet<Specimen> CollectionSpecimen { get; set; }
        public virtual DbSet<SpecimenImage> CollectionSpecimenImage { get; set; }
        public virtual DbSet<Identification> Identification { get; set; }
        public virtual DbSet<IdentificationUnit> IdentificationUnit { get; set; }
        public virtual DbSet<IdentificationUnitAnalysis> IdentificationUnitAnalysis { get; set; }
        public virtual DbSet<IdentificationUnitGeoAnalysis> IdentificationUnitGeoAnalysis { get; set; }
        public virtual DbSet<CollectionAgent> CollectionAgent { get; set; }
        public virtual DbSet<Property> Property { get; set; }
    
        public virtual ObjectResult<UserTaxonList> DiversityMobile_UserTaxonLists(string loginName)
        {
            var loginNameParameter = loginName != null ?
                new ObjectParameter("LoginName", loginName) :
                new ObjectParameter("LoginName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserTaxonList>("DiversityMobile_UserTaxonLists", loginNameParameter);
        }
    
        public virtual ObjectResult<UserTerminology> DiversityMobile_UserTerminologies(string loginName)
        {
            var loginNameParameter = loginName != null ?
                new ObjectParameter("LoginName", loginName) :
                new ObjectParameter("LoginName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserTerminology>("DiversityMobile_UserTerminologies", loginNameParameter);
        }
    }
}
