//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityService.DB.Collection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Images = new HashSet<EventImage>();
            this.Properties = new HashSet<EventProperty>();
            this.Specimen = new HashSet<Specimen>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SeriesID { get; set; }
        private Nullable<byte> CollectionDay { get; set; }
        private Nullable<byte> CollectionMonth { get; set; }
        private Nullable<short> CollectionYear { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string LocalityDescription { get; set; }
        public string HabitatDescription { get; set; }
        public string Notes { get; set; }
        public System.Guid TransactionGuid { get; set; }
        public int Version { get; set; }
        private string CollectionTime { get; set; }
        private string CollectionDateCategory { get; set; }
    
        public virtual EventSeries Series { get; set; }
        public virtual ICollection<EventImage> Images { get; set; }
        public virtual ICollection<EventProperty> Properties { get; set; }
        public virtual ICollection<Specimen> Specimen { get; set; }
    }
}
