//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityService.Collection
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentificationUnitGeoAnalysis
    {
        public int SpecimenId { get; set; }
        public int IdentificationUnitId { get; set; }
        public System.DateTime AnalysisDate { get; set; }
        public System.Data.Entity.Spatial.DbGeography Geography { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Geometry { get; set; }
        public string ResponsibleName { get; set; }
        public string ResponsibleAgentURI { get; set; }
        public string Notes { get; set; }
        public System.Guid RowGUID { get; set; }
    
        public virtual IdentificationUnit IdentificationUnit { get; set; }
    }
}
