//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityService.Collection
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentificationUnitAnalysis
    {
        public int CollectionSpecimenID { get; set; }
        public int IdentificationUnitID { get; set; }
        public int AnalysisID { get; set; }
        public string AnalysisNumber { get; set; }
        public string AnalysisResult { get; set; }
        public string ExternalAnalysisURI { get; set; }
        public string ResponsibleName { get; set; }
        public string ResponsibleAgentURI { get; set; }
        public string AnalysisDate { get; set; }
        public Nullable<int> SpecimenPartID { get; set; }
        public Nullable<int> ToolID { get; set; }
        public string Notes { get; set; }
        public System.Guid RowGUID { get; set; }
        public string ToolUsage { get; set; }
    
        public virtual Analysis Analysis { get; set; }
        public virtual IdentificationUnit IdentificationUnit { get; set; }
    }
}
