//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityService.Collection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identification
    {
        public int CollectionSpecimenID { get; set; }
        public int IdentificationUnitID { get; set; }
        public short IdentificationSequence { get; set; }
        public Nullable<System.DateTime> IdentificationDate { get; set; }
        public Nullable<byte> IdentificationDay { get; set; }
        public Nullable<byte> IdentificationMonth { get; set; }
        public Nullable<short> IdentificationYear { get; set; }
        public string IdentificationDateSupplement { get; set; }
        public string IdentificationDateCategory { get; set; }
        public string VernacularTerm { get; set; }
        public string TaxonomicName { get; set; }
        public string NameURI { get; set; }
        public string IdentificationCategory { get; set; }
        public string IdentificationQualifier { get; set; }
        public string TypeStatus { get; set; }
        public string TypeNotes { get; set; }
        public string ReferenceTitle { get; set; }
        public string ReferenceURI { get; set; }
        public string Notes { get; set; }
        public string ResponsibleName { get; set; }
        public string ResponsibleAgentURI { get; set; }
        public System.Guid RowGUID { get; set; }
        public string ReferenceDetails { get; set; }
    
        public virtual IdentificationUnit IdentificationUnit { get; set; }
    }
}
