//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityService.DB.Collection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public Property()
        {
            this.CollectionEventProperty = new HashSet<EventProperty>();
            this.Property1 = new HashSet<Property>();
        }
    
        public int PropertyID { get; set; }
        public Nullable<int> PropertyParentID { get; set; }
        public string PropertyName { get; set; }
        public string DefaultAccuracyOfProperty { get; set; }
        public string DefaultMeasurementUnit { get; set; }
        public string ParsingMethodName { get; set; }
        public string DisplayText { get; set; }
        public Nullable<bool> DisplayEnabled { get; set; }
        public Nullable<short> DisplayOrder { get; set; }
        public string Description { get; set; }
        public System.Guid RowGUID { get; set; }
    
        public virtual ICollection<EventProperty> CollectionEventProperty { get; set; }
        public virtual ICollection<Property> Property1 { get; set; }
        public virtual Property Property2 { get; set; }
    }
}
