//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityService.DB.Collection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specimen
    {
        public Specimen()
        {
            this.CollectionSpecimenImage = new HashSet<SpecimenImage>();
            this.IdentificationUnit = new HashSet<IdentificationUnit>();
            this.CollectionAgent = new HashSet<CollectionAgent>();
        }
    
        public int Id { get; set; }
        public int Version { get; set; }
        public Nullable<int> EventID { get; set; }
        public string AccessionNumber { get; set; }
        public Nullable<System.DateTime> AccessionDate { get; set; }
        public Nullable<byte> AccessionDay { get; set; }
        public Nullable<byte> AccessionMonth { get; set; }
        public Nullable<short> AccessionYear { get; set; }
        public string AccessionDateCategory { get; set; }
        public string DepositorsName { get; set; }
        public string DepositorsAgentURI { get; set; }
        public string DepositorsAccessionNumber { get; set; }
        public string LabelTitle { get; set; }
        public string LabelType { get; set; }
        public string LabelTranscriptionState { get; set; }
        public string LabelTranscriptionNotes { get; set; }
        public string ExsiccataURI { get; set; }
        public string ExsiccataAbbreviation { get; set; }
        public string OriginalNotes { get; set; }
        public string AdditionalNotes { get; set; }
        public string ReferenceTitle { get; set; }
        public string ReferenceURI { get; set; }
        public string ReferenceDetails { get; set; }
        public string Problems { get; set; }
        public string DataWithholdingReason { get; set; }
        public string InternalNotes { get; set; }
        public Nullable<int> ExternalDatasourceID { get; set; }
        public string ExternalIdentifier { get; set; }
        public bool xx_IsAvailable { get; set; }
        public System.Guid TransactionGuid { get; set; }
    
        public Event CollectionEvent { get; set; }
        public ICollection<SpecimenImage> CollectionSpecimenImage { get; set; }
        public ICollection<IdentificationUnit> IdentificationUnit { get; set; }
        public ICollection<CollectionAgent> CollectionAgent { get; set; }
    }
}
