//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityService.Collection
{
    using System;
    
    public partial class UserTaxonList
    {
        public string DataBaseName { get; set; }
        public Nullable<int> ListID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string DataSource { get; set; }
        public string DisplayText { get; set; }
        public string TaxonomicGroup { get; set; }
    }
}
