//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityService.DB.Collection
{
    using System;
    
    public partial class UserTerminology
    {
        public string DataBaseName { get; set; }
        public Nullable<int> TerminologyID { get; set; }
        public string DisplayText { get; set; }
    }
}
