//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityService.Mobile
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mobile : DbContext
    {
        public Mobile()
            : base("name=Mobile")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TaxRef_BfN_VPlants> TaxRef_BfN_VPlants { get; set; }
        public virtual DbSet<TaxRef_DGfM_Fungi> TaxRef_DGfM_Fungi { get; set; }
        public virtual DbSet<TaxRef_LIAS_Erys_DE> TaxRef_LIAS_Erys_DE { get; set; }
        public virtual DbSet<TaxRef_LIAS_Lichens_DE> TaxRef_LIAS_Lichens_DE { get; set; }
        public virtual DbSet<TaxRef_LIAS_LichFungi_DE> TaxRef_LIAS_LichFungi_DE { get; set; }
        public virtual DbSet<Terms_LebensraumTypen> Terms_LebensraumTypen { get; set; }
        public virtual DbSet<Terms_Pflanzengesellschaften> Terms_Pflanzengesellschaften { get; set; }
    }
}
