//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityService.Mobile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terms_Pflanzengesellschaften
    {
        public int PropertyID { get; set; }
        public string PropertyURI { get; set; }
        public string DisplayText { get; set; }
        public string HierarchyCache { get; set; }
        public int TermID { get; set; }
        public Nullable<int> BroaderTermID { get; set; }
    }
}
