﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using DiversityService.API.Model;
using Refit;
using System.Threading.Tasks;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace DiversityService.API.Client
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedISeriesAPI : ISeriesAPI
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedISeriesAPI(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<IEnumerable<EventSeries>> GetAll(int take,int skip)
        {
            var arguments = new object[] { take,skip };
            return (Task<IEnumerable<EventSeries>>) methodImpls["GetAll"](Client, arguments);
        }

        public virtual Task<IEnumerable<EventSeries>> Get(int id,int take,int skip)
        {
            var arguments = new object[] { id,take,skip };
            return (Task<IEnumerable<EventSeries>>) methodImpls["Get"](Client, arguments);
        }

        public virtual Task<EventSeries> Create(EventSeriesUpload es)
        {
            var arguments = new object[] { es };
            return (Task<EventSeries>) methodImpls["Create"](Client, arguments);
        }

    }
}


